#!/usr/bin/env bash
# setup.sh — jobautopilot skill bundle first-time setup
#
# Run this once after installing the skills:
#   bash setup.sh
#
# What it does:
#   1. Asks you a few questions
#   2. Writes ~/.openclaw/users/<you>/config.sh with your info
#   3. Creates the workspace folders and tracker file
#   4. Copies scripts to the right places
#   5. Prints a quick-start guide

set -e
SKILL_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

echo ""
echo "=== jobautopilot skill bundle — first-time setup ==="
echo ""

# ── 1. Collect user info ───────────────────────────────────────────────────────

read -rp "OpenClaw username (same as 'openclaw whoami'): " OPENCLAW_USER
read -rp "First name: " USER_FIRST_NAME
read -rp "Last name:  " USER_LAST_NAME
read -rp "Email:      " USER_EMAIL
read -rp "Phone (e.g. +1-212-555-0000): " USER_PHONE
read -rp "LinkedIn URL: " USER_LINKEDIN
echo ""
read -rp "Resume folder (where your original .docx resumes live) [~/Documents/jobs/]: " RESUME_DIR
RESUME_DIR="${RESUME_DIR:-$HOME/Documents/jobs/}"
read -rp "Tailored output folder [~/Documents/jobs/tailored/]: " RESUME_OUTPUT_DIR
RESUME_OUTPUT_DIR="${RESUME_OUTPUT_DIR:-$HOME/Documents/jobs/tailored/}"
echo ""
read -rp "Job search location [New York City]: " JOB_SEARCH_LOCATION
JOB_SEARCH_LOCATION="${JOB_SEARCH_LOCATION:-New York City}"
read -rp "Search keywords (space-separated) [quant risk python c++ developer]: " JOB_SEARCH_KEYWORDS
JOB_SEARCH_KEYWORDS="${JOB_SEARCH_KEYWORDS:-quant risk python c++ developer}"
read -rp "Minimum base salary (leave blank to skip filter): " JOB_SEARCH_MIN_SALARY
read -rp "Max listing age in days [90]: " JOB_SEARCH_MAX_AGE_DAYS
JOB_SEARCH_MAX_AGE_DAYS="${JOB_SEARCH_MAX_AGE_DAYS:-90}"
echo ""

echo "--- EEOC defaults (used in application forms, press Enter to accept) ---"
read -rp "Gender [Male]: " USER_GENDER;       USER_GENDER="${USER_GENDER:-Male}"
read -rp "Race [Asian]: " USER_RACE;           USER_RACE="${USER_RACE:-Asian}"
read -rp "Hispanic/Latino [No]: " USER_HISPANIC; USER_HISPANIC="${USER_HISPANIC:-No}"
read -rp "Veteran status [I have no military service]: " USER_VETERAN
USER_VETERAN="${USER_VETERAN:-I have no military service}"
read -rp "Disability [No]: " USER_DISABILITY;  USER_DISABILITY="${USER_DISABILITY:-No}"
read -rp "Work authorized in US? [Yes]: " USER_WORK_AUTH; USER_WORK_AUTH="${USER_WORK_AUTH:-Yes}"
read -rp "Require sponsorship? [No]: " USER_NEED_SPONSOR; USER_NEED_SPONSOR="${USER_NEED_SPONSOR:-No}"

# ── 2. Create directories ──────────────────────────────────────────────────────

WORKSPACE="$HOME/.openclaw/workspace/job_search"
SCRIPTS_DIR="$HOME/.openclaw/workspace/job_sub_agent/scripts"
CONFIG_DIR="$HOME/.openclaw/users/${OPENCLAW_USER}"

mkdir -p "$WORKSPACE"
mkdir -p "$SCRIPTS_DIR"
mkdir -p "$CONFIG_DIR"
mkdir -p "$RESUME_DIR"
mkdir -p "$RESUME_OUTPUT_DIR"

# ── 3. Write config.sh ────────────────────────────────────────────────────────

cat > "$CONFIG_DIR/config.sh" << EOF
# jobautopilot skill bundle — user config
# Generated by setup.sh on $(date +%Y-%m-%d)
# Edit any value here; re-run setup.sh to regenerate from scratch.

export OPENCLAW_USER="${OPENCLAW_USER}"
export OPENCLAW_PROFILE="apply"        # browser profile used for submitting applications

# Personal info
export USER_FIRST_NAME="${USER_FIRST_NAME}"
export USER_LAST_NAME="${USER_LAST_NAME}"
export USER_EMAIL="${USER_EMAIL}"
export USER_PHONE="${USER_PHONE}"
export USER_LINKEDIN="${USER_LINKEDIN}"

# File paths
export RESUME_DIR="${RESUME_DIR}"
export RESUME_OUTPUT_DIR="${RESUME_OUTPUT_DIR}"
export RESUME_TEMPLATE="\$HOME/.openclaw/workspace/job_sub_agent/scripts/sample_placeholders.docx"
export MD_TO_DOCX_SCRIPT="\$HOME/.openclaw/workspace/job_sub_agent/scripts/md_to_docx.py"
export TRACKER_PATH="\$HOME/.openclaw/workspace/job_search/job_application_tracker.md"
export CHECK_FIELDS_JS="\$HOME/.openclaw/workspace/job_sub_agent/scripts/check_required_fields.js"

# Search settings
export JOB_SEARCH_LOCATION="${JOB_SEARCH_LOCATION}"
export JOB_SEARCH_KEYWORDS="${JOB_SEARCH_KEYWORDS}"
export JOB_SEARCH_MIN_SALARY="${JOB_SEARCH_MIN_SALARY}"
export JOB_SEARCH_MAX_AGE_DAYS="${JOB_SEARCH_MAX_AGE_DAYS}"
export JOB_SEARCH_HANDOFF="\$HOME/.openclaw/workspace/job_search/SEARCH_BOT_HANDOFF.md"

# EEOC defaults
export USER_GENDER="${USER_GENDER}"
export USER_RACE="${USER_RACE}"
export USER_HISPANIC="${USER_HISPANIC}"
export USER_VETERAN="${USER_VETERAN}"
export USER_DISABILITY="${USER_DISABILITY}"
export USER_WORK_AUTH="${USER_WORK_AUTH}"
export USER_NEED_SPONSOR="${USER_NEED_SPONSOR}"
EOF

echo "✅  Config written to $CONFIG_DIR/config.sh"

# ── 4. Copy scripts to workspace ──────────────────────────────────────────────

cp "$SKILL_DIR/jobautopilot-tailor/scripts/md_to_docx.py"          "$SCRIPTS_DIR/"
cp "$SKILL_DIR/jobautopilot-tailor/scripts/sample_placeholders.docx" "$SCRIPTS_DIR/"
cp "$SKILL_DIR/jobautopilot-submitter/scripts/check_required_fields.js"    "$SCRIPTS_DIR/"
cp "$SKILL_DIR/jobautopilot-submitter/scripts/fill_template.sh"            "$SCRIPTS_DIR/"
cp "$SKILL_DIR/jobautopilot-submitter/scripts/match_variant_options.sh"    "$SCRIPTS_DIR/"
cp "$SKILL_DIR/jobautopilot-submitter/ERRORS.md" \
   "$HOME/.openclaw/workspace/job_sub_agent/ERRORS.md"

echo "✅  Scripts copied to $SCRIPTS_DIR"

# ── 5. Create browser profiles ────────────────────────────────────────────────

echo ""
echo "==> Setting up browser profiles..."

# Create browser profiles — safe to re-run, existing profiles are skipped
for PROFILE in search apply; do
  EXISTING=$(openclaw browser profile list 2>/dev/null || true)
  if echo "$EXISTING" | grep -q "^${PROFILE}$"; then
    echo "ℹ️   Browser profile '${PROFILE}' already exists — skipped"
  else
    openclaw browser profile create "$PROFILE" 2>/dev/null       && echo "✅  Browser profile '${PROFILE}' created"       || { echo "⚠️   Could not create browser profile '${PROFILE}' — run manually:";            echo "    openclaw browser profile create ${PROFILE}"; }
  fi
done

# ── 6. Init tracker and handoff files ─────────────────────────────────────────

TRACKER="$WORKSPACE/job_application_tracker.md"
HANDOFF="$WORKSPACE/SEARCH_BOT_HANDOFF.md"

if [ ! -f "$TRACKER" ]; then
cat > "$TRACKER" << 'EOF'
# Job Application Tracker

| Company | Title | Location | URL | Posted | Salary | Status | Notes |
|---------|-------|----------|-----|--------|--------|--------|-------|
EOF
  echo "✅  Tracker created at $TRACKER"
else
  echo "⏭   Tracker already exists — not overwritten"
fi

if [ ! -f "$HANDOFF" ]; then
  echo "# Search Bot Handoff" > "$HANDOFF"
  echo "✅  Handoff file created"
fi

# ── 6. Quick-start guide ──────────────────────────────────────────────────────

echo ""
echo "============================================================"
echo "  Setup complete! Quick-start guide:"
echo "============================================================"
echo ""
echo "  STEP 1 — Search for jobs"
echo "    Tell OpenClaw: 'Run the jobautopilot/search skill'"
echo "    Agent reads your config, searches LinkedIn,"
echo "    and writes results to your tracker."
echo ""
echo "  STEP 2 — Tailor your resume"
echo "    Tell OpenClaw: 'Run the jobautopilot/tailor skill'"
echo "    Agent picks up 'shortlist' jobs from tracker,"
echo "    tailors resume + cover letter, saves .docx files."
echo ""
echo "  STEP 3 — Submit applications"
echo "    Tell OpenClaw: 'Run the jobautopilot/submit skill'"
echo "    Agent fills and submits forms for 'resume_ready' jobs."
echo ""
echo "  Your config: $CONFIG_DIR/config.sh"
echo "  Tracker:     $TRACKER"
echo "  Outputs:     $RESUME_OUTPUT_DIR"
echo ""
echo "  To update your info later, edit config.sh directly"
echo "  or re-run: bash setup.sh"
echo "============================================================"
